language: julia
os:
- linux
julia:
- 1.2
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
  - shards
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_SHARDS_DIR=shards
  - BINARYBUILDER_AUTOMATIC_APPLE=true
  - BINARYBUILDER_USE_CCACHE=true
  matrix:
  - TARGET=i686-linux-gnu
  - TARGET=x86_64-linux-gnu
  - TARGET=aarch64-linux-gnu
  - TARGET=arm-linux-gnueabihf
  - TARGET=powerpc64le-linux-gnu
  - TARGET=i686-linux-musl
  - TARGET=x86_64-linux-musl
  - TARGET=aarch64-linux-musl
  - TARGET=arm-linux-musleabihf
  - TARGET=x86_64-apple-darwin14
  - TARGET=x86_64-unknown-freebsd11.1
  - TARGET=i686-w64-mingw32
  - TARGET=x86_64-w64-mingw32
sudo: required
jobs:
  include:
  - stage: regenerate build.jl
    script: julia --color=yes build_tarballs.jl --only-buildjl
    if: tag IS present
before_script:
- julia -e 'using Pkg; pkg"add BinaryProvider BinaryBuilder#master; build"'
script:
- julia --color=yes build_tarballs.jl $TARGET
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key:
    secure: c6rD8+3qEQvHbATO7+g0HEMdvL8jO9JynJ67F8OE0iEcE3+fB+0nt/92aay307Tc8+5N5XwY1UcLLLkvNgbNLQPCMwUZgw+OsA34g+ISj0p83z2tiFkNAXNE5Km+DBjXh+gCTf+P6yBdE3rga47mZW3/PxlUNfMf4KkU4by5wOUn6VhC8yVQ6iGO985pufomw9oyxjkaYNRatZnkWzHNT4pIgERVyGzXFa1Zm99qmeISCGTp4NTZ33T4BQzFq/oCTamUZItpMzFMKWQ6bDFd41k5u64E7+0vMiw9PFcNxAj1BWwN8HnHmk+XZaz5kpxMu2b38m27ERSjf3edo7ZlTK4nciuNGFg1qKtXmyQewa8bJBZcRkZl9cEhCBnLnNm5SJWSnAsLOZHSi5Gs8Vh2mlosnsRY2cst6AGsnHQvMZG0JaJczZsO7ksiidjYsXZ01d1gs0J3pNUIgFD9k/MIqWhWdAkNRtlJMFL3eq8DzbqlVvIpOZPJ657PTF7uJLxm0mJ+Pa+e5wu1QGxHDHh3+QZ2LLdyTKdVG2uKiMGiyasJsLjbVmfjQhMP1Ft/Qs29xc0FWdcEdxM6ehvArsI4HPGPq34w4tV8qFoZLKW2782R8GTgd0nn3iHpAhu+KslTp46Wq6f8DBVQYVXWHNPVUmk+JYqD+xc+M1VKwAt04vQ=
  file: products/*
  on:
    repo: JuliaIO/FFMPEGBuilder
    tags: true
