language: julia
os:
- linux
julia:
- 1.2
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
  - shards
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_SHARDS_DIR=shards
  - BINARYBUILDER_AUTOMATIC_APPLE=true
  - BINARYBUILDER_USE_CCACHE=true
  matrix:
  - TARGET=i686-linux-gnu
  - TARGET=x86_64-linux-gnu
  - TARGET=aarch64-linux-gnu
  - TARGET=arm-linux-gnueabihf
  - TARGET=powerpc64le-linux-gnu
  - TARGET=i686-linux-musl
  - TARGET=x86_64-linux-musl
  - TARGET=aarch64-linux-musl
  - TARGET=arm-linux-musleabihf
  - TARGET=x86_64-apple-darwin14
  - TARGET=x86_64-unknown-freebsd11.1
  - TARGET=i686-w64-mingw32
  - TARGET=x86_64-w64-mingw32
sudo: required
jobs:
  include:
  - stage: regenerate build.jl
    script: julia --color=yes build_tarballs.jl --only-buildjl
    if: tag IS present
before_script:
- julia -e 'using Pkg; pkg"add BinaryProvider BinaryBuilder#master; build"'
script:
- julia --color=yes build_tarballs.jl $TARGET
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key:
    secure: r11KGHpckBtvKDBjpAMQZ8XGWNDnu7YLbGVQ3pSOaLQc3xmRGXlRgINERsiaRBfpr5BOIoBG/EPU0vT2HvWIuBLX+CvHmnjO+AcHEPQ3HLHhsOfp2INd91m7/WyWeAUyQxOUIBVpVd9Uj5B5XprO3wbRsbGYHUCHfhqaQ9pCOd/EyYXx1TP0cyXvyK91dZE7gebLwjYVnePysO6s7C7uNMOHMUpSAiQGQukqr9IYhp5gj1NOI4r4FPm1CTlEGzo/brFZ2ylA0azy1O+NYW056APdOQFH6PxhTwOpnK1EH1FFXvHwq2yjYrhPYk2HgKImven3y13n/KwNqWa2oOcNNs09RwPtOjcdTu3TMx+Vidgiwef6CK9njn+Kx6AtlWxT+FTpy9If5XgNt4nM0V6UEVSKVyJWblDicEaBeiSZxl3HiKnTzSKIj6bx/AbSofeQB9ogS6haVhC7nAUGcb/iyctJ+Ry62XmeaTfoAbVM+kRS2zH9M6e1pNnFcAGZ8gCDBp8Oote+WlCJK5eoBsYJLzxXzPQVQxMLaKZZVba3BhTCQGna8EmtVqK/o9UcD1fObrQwTXHCpOOf8p9VaGYTAz0RY4jQGBFBY/cMzH/YieC4b0iIECNpTF1fxvMwPYrrTb6XJDeBr7d39SPmiQdXUOPeToTFaCdPNOk/sCIpP4I=
  file: products/*
  on:
    repo: JuliaIO/FFMPEGBuilder
    tags: true
